In [1]:
import pandas as pd

there are 2 core objects in pandas : DataFrame and Series
# DataFrame
A DataFrame is a table. It contains an array of individual entries, each of which has a certain value. Each entry corresponds to a row (or record) and a column.

In [2]:
# data frame examples
pd.DataFrame({'Yes' : [50, 21], 'No' : [131, 2]})

   Yes   No
0   50  131
1   21    2

In this example, the "0, No" entry has the value of 131. The "0, Yes" entry has a value of 50, and so on.

In [3]:
pd.DataFrame({'bob' : ['i like it', 'it was awful'], 'sue':['pretty good', 'bad']})

            bob          sue
0     i like it  pretty good
1  it was awful          bad

In [5]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 
                'Sue': ['Pretty good.', 'Bad.']},
                index=['Product A', 'Product B'])

                     Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.          Bad.

# Series
A Series, by contrast, is a sequence of data values. If a DataFrame is a table, a Series is a list. And in fact you can create one with nothing more than a list:

In [6]:
pd.Series([1,2,3,4,5,6,7])

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

A Series is, in essence, a single column of a DataFrame. So you can assign row labels to the Series the same way as before, using an index parameter. However, a Series does not have a column name, it only has one overall name:

In [7]:
pd.Series([30,40,50], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product Sales')

2015 Sales    30
2016 Sales    40
2017 Sales    50
Name: Product Sales, dtype: int64

 # Reading data files
 CSV file is a table of values separated by commas. Hence the name: "Comma-Separated Values", or CSV.

In [13]:
# importing the data set
# url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
# df = pd.read_csv(url)
# df.head()
df = pd.read_csv("datasets/titanic.csv")

In [ ]:
df.head() # returns the 1st five rows of the data set by default

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.shape # property used to descripe the shape of the dataset (rows X columns)

(891, 12)

In [ ]:
df.columns # returns the list of the columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [ ]:
df.info() # gives info about the dataset data types, non null count column names etc

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [ ]:
df.tail() # returns the last 5 rows of the dataset

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [20]:
df.index # df.index == row labels

RangeIndex(start=0, stop=891, step=1)

In [21]:
df.dtypes # mentions the data types of the columns

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

| Pandas dtype | Meaning             |
| ------------ | ------------------- |
| `int64`      | Integer             |
| `float64`    | Decimal number      |
| `object`     | Usually text/string |
| `bool`       | True/False          |
| `datetime64` | Date/time           |

In [23]:
df["Age"].dtype

dtype('float64')

In [24]:
df["Sex"].dtype

In [25]:
df.describe() # statistical summary of the numerical columns

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

### count

Number of non-missing values.

### mean

Average.

### std

Standard deviation — how spread out the values are.

### min

Smallest value.

### 25%

First quartile.

### 50%

Median.

### 75%

Third quartile.

### max

Largest value.

### describe
describe() = quick statistical overview of your numerical data.

In [27]:
df["Fare"].describe()

count    891.000000
mean      32.204208
std       49.693429
min        0.000000
25%        7.910400
50%       14.454200
75%       31.000000
max      512.329200
Name: Fare, dtype: float64

In [ ]:
df["Age"] # selecting only one column its a series

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

DataFrame

↓

column

↓

Series

A Series is essentially one-dimensional labeled data.

In [29]:
age = df["Age"]
type(age)

pandas.Series

In [31]:
age.shape

(891,)

In [33]:
df[["Age"]].shape

(891, 1)

In [30]:
# selecting multiple columns
df[["Age", "Fare", "Sex"]]

      Age     Fare     Sex
0    22.0   7.2500    male
1    38.0  71.2833  female
2    26.0   7.9250  female
3    35.0  53.1000  female
4    35.0   8.0500    male
..    ...      ...     ...
886  27.0  13.0000    male
887  19.0  30.0000  female
888   NaN  23.4500  female
889  26.0  30.0000    male
890  32.0   7.7500    male

[891 rows x 3 columns]

The outer [] is the DataFrame selection operation.

The inner [] is a Python list containing the column names:

In [34]:
type(df[["Fare"]])

pandas.DataFrame

In [35]:
type(df["Fare"])

pandas.Series

In [36]:
df["Fare"].shape

(891,)

In [37]:
df[["Fare"]].shape

(891, 1)